-- Count unique customers

SELECT
    COUNT(DISTINCT customer_id) AS total_customers
FROM orders;

-- Revenue per customer

SELECT
    customer_id,
    SUM(revenue) AS total_revenue
FROM orders
GROUP BY customer_id
ORDER BY total_revenue DESC;

-- Order per customer

SELECT
    customer_id,
    COUNT(*) AS total_orders,
    SUM(revenue) AS total_revenue
FROM orders
GROUP BY customer_id
ORDER BY total_revenue DESC
LIMIT 5;

-- Total company revenue 

SELECT
    SUM(revenue) AS total_revenue
FROM orders;

-- Revenue generated by top customer (customer_id = 1093)

SELECT
    SUM(revenue) AS customer_revenue
FROM orders
WHERE customer_id = 1093;